package DICAS;






public class variadas {
	public static void main(String[] args) {
		/**
		 * DIGITA JOp + CTRL + ESPAÇO = JOptionPane AE COLOCA .showInputDialog CHAMA UM PROMPT;
	     *String valo1 = JOptionPane.showInputDialog("digite o primeiro numero:");//7.9
	     
	     *******CONSTRUTOR*******
	     *É UM METODO ESPECIAL
	     *QUE NAO TEM RETORNO E NOME DA CLASS TEM QUE SR IGUAL AO DO CONSTRUTOR; 
	     *
	     *****PAR OU IMPAR*****
	     *SO FAZER O MUDOLO DE UM NIMERO POR 2
	     *QUALQUER NUMERO MODULO (%) 2 SE O RESULTADO FOR ZERO É PAR SE FOR 1 É IMPAR
	     *
		 *SE O METODO FOR STATIC VC PODE ACESSAR DIRETAMENTE DA CLASS SEM NECESSIDADE DE ESTANCIAR;
		 * 
		 * INCREMENTO ++
		 * DECREMENTO --
		 * 
		 * INTANCIADO: CRIADO; ATRIBUIDO... QUANDO SE CRIA OBJETO E SA DA UMA UTILIDADE A ELE SE DIZ INTANCIAR OBJETO
		 * *****************************************************************
		 * ********** REVEJA A AULA 108 VARIAS VEZES ************************************
		 * **************************************************************
		 * ***********VALOR VS REFERENCIA****************
		 * PRIMITIVOS A ATRIBUIÇAO É FEITA POR VALOR;
		 * OBJETOS A ATRIBUIÇAO É FEIRA POR REFERÊNCIA;
		 * 
		 * 
		 *System.out.printf("i = %d\n", contador);  
		 * SEMPRE QUE USAR O (%) + d OU i TEM QUE TROCAR O PRINTLN POR PRINTF; %d %i;
		 * 
		 * O (STATIC) DIZ QUE O VALOR ASSOCIADO A ESSE ATRIBUTO NAO PERTENCE MAIS A INSTANCIA E SIM A CLASS;
		 * UM METODO STATIC SO CONSEGUE ACESSAR OUTRO METDOD STATIC (REGRA) VC VANO CONSEGUE A PARTIR DUM METODO 
		 * STATICO ACESSAR UM METORDO DE INSTANCIA;
		 * 
		 * 
		 * //@SuppressWarnings({ "rawtypes", "unchecked" }) -> SILENCIA ADIVERTENCIAS (CTRL + 1)
		 * 
		 * //PRA GERAR HASHCODE E EQUALS -> BOTAO DIREITO -> SOURCE -> GENERATE HASHCODO() AND EQUALS();
		 * 
		 * Produto.desconto = 0.50;// SEMPRE CODIFICAR DE UMA FORMA EXPLICITA (EX:Produto.desconto) AQUI EU TM PODERIA COLOCAR (EX: p2. ou p1.) 
		 *E ALTERAR O VALOR DO DESCONTO MAIS POR BAIXO DUMA FORMA IMPLICITA O JAVA DARIA DESCONTO NO GERAL. JA QUE É PRA SER O DESCONTE
		 *GERAL SE COMO COLCAR EXPLICITAMENTE (EX:Produto.desconto);
		
		 * 
		 * Scanner entrada = new Scanner (System.in);
		 *  System.out.print("Digite a note: ");
		 * double nota = entrada.nextDouble();
		 * entrada.close();
		 *
		 *
		 *PREFERENCIAS -> TEMPLATE -> VAJA EDITDOR TAMPLATE
		 *VC CRIA TRECHOS DE COD QUE PODE SER USADO PELA IDE; TIPO syso...
		 *
		 *%.2f DIMINUI AS CASAS DECIMAIS EM NUMEROS DOUBLE
		 *
		 *REFATORAR UM CODIGO QUER DIZER MODIFICAR (TORNA LO MELHOR);
		 *QUANDO CHAMA COM () VC ESTA CHAMANDO O METODO "COMPORTAMENTO" E QUANDO CHAMA SEM OS () VC ESTA
		 *CHAMANDO OS ATRIBUTOS;
		 *
		 *TUDO QUE FOR METODO (COMPORTAMENTO) OBRIGATORIAMENTE TEM QUE TER ();
		 *
		 ***********************ARREY*******************
		 *ELE É HOMOGENIO, TEM UMA ESTRUTURA FIXA (TODOS OS DADOS SAO DO MESO TIPO)
		 *É ENUMEREADO E SEMPRE COMEÇA DO ZERO;
		 *ARREY MULTDIMENCIONAL -> [] []....;(UM ARRAY DENTRO DO OUTRO;
		 *
		 * ********* POO ************
		 * APP (APILCAÇAO) É UM CONJUNTO DE CLASSES DENTRO DUM PACOTE;
		 * 
		 * ctrl + m maximizar tela
		 * 
		 * ctrl + shit + O -> limpa os imports;
		 * 
		 * ALT + TAB -> MOVER ENTRE TELAS;
		 * 
		 * CTRL + SHIFT + F -> REORGANIZA O CODIGO;
		 * 
		 * SE UM  METODO FOR EX: STRING ELE TEM QTE TER RETURN STRING, SE DOR VOID NAO TEM O RETURN
		 * 
		 * ABSTRACT faz com que a class nao posso ser instanciada (modificada) ela serve somente de modelo (base);
		 * 
		 * STATIC ====> NO PADRAO TODA VARIAVEL PERTECE AO OBJETO, TODA CONSTANTE PERTECE AO OBJETO, 
		 *  TODO METODO PERTENCE AO OBJETO
		 *  QUANDO SE USA **STATIC**  TODA VARIAVEL PASSA A PERTENCER A CLASSE, TODA CONSTANTE PASSA A PERTECE AO CLASSE, 
		 *  TODO METODO PASSA A PERTENCE A CLASSE.
		 * METODO STATIC ME PERMITE USAR A CLASS MESMO SEM SER INSTANCIADA; 
           METODO STATIC NAO ARMAZENA VALORES;
           SEMPRE QUE TIVER UM METODO QUE VA FAZER UMA CONVERÇAO EM USO O METODO STATIC;
		 *  
		 * METODO == COMPORTAMENTO;
		 * 
		 * STATIC ====> SO PODE SER USADO PELA CLASSE... NAO PODE SER INSTANCIAOD 
		 * ASSISTA ESSA EXEMPLI SO UTUBE ===> https://www.youtube.com/watch?v=KmwloIBFNpY
		 * 
		 * FINAL =====> https://www.youtube.com/watch?v=Uhph07-JfZs
		 * FINAL ===> PODE SER INSERIDO EM CLASSES, ATRUBUTOS E METODOS
		 *** FINAL CLASSE-> ELE VAI DEIXAR SUA CLASSE FINAL E ELE NAO VAI PODER SER ENCHERGADA POR NENHUMA OUTRA CLASSE;
		 * VC INSERE O FINAL NA CLASSE QUANDO ELA FOR MUITO ESPECIFICA.
		 * ** FINAL ATRIBUTO -> QUANDO VC INSERE UM ATRIBUTO QUE NUNCA MUDARA, VC COLOCA FINAL E ELE NAO É MAIS MODIFICADO.
		 * ** FINAL METODOS-> O METODO NAO PODE SER SOBREECTRICO;
		 *MOTODO TOSTRING ===> https://www.youtube.com/watch?v=3Wo2kKDQ9T0
		 * HASHCODE E EQUALS ===> https://www.youtube.com/watch?v=NPJBmZfZmYI
		 * HASHCODE É UMA SEQUENCIA DE CARACTERES QUE INDENTIFICA O OBJETO;
		 * 
		 * COPIAR CLASSE => CLICA NA CLASSE E CTRL C + CTRL V;
		 * 
		 * CTRL + SHIFT + O ==> FAZ IMPORTS 
		 * ALT + SHIT + S ==> GERAR CONSTRUTORES;
		 * CTRL + 1 ==> CLICA EN CIMA DO METODO NA EXISTENTE E CRIAR METODO;		 * 
		 * 
		 *RENOMEAR TUDO DE UMA SO VEZ ==> CTRL + 1;
		 * 
		 *  (lista.size() - 1 )==> PEGA O ULTIMO ELEMENTO DA LISTA
		 * 
		 * CONTROL + SHIFT + T ==> eventos (PADROESOBSERVER)
		 * 
		 * CTRL + D vai apagando as linhas....
		 * 
		 * ALT + SHIF + S CRIAR CONSTRUTORES
		 * CTRL + SHIT + T = VER INTERFACES
		 * CTRL + O = ATALHO PARA VER OS METODOS;
		 * 
		 * MYSQL É UMA LINGUAGEM CASEINSENSITIVE ELA NAO LIGA PRA MAIUSCULAS OU MINUSCULAS
		 * 
		 */
		
		
	}
}
